import Testing
import UIKit
@testable import yuedu_app

/// Phase 2A A/B diagnostic harness.
///
/// Runs BOTH engines on each corpus book/chapter independently of the reader
/// UI and collects: capability accept/reject, page counts, first-page latency,
/// full layout time, peak memory, text parity, and first-3-page snapshots of
/// each engine. Snapshots go to a LOCAL artifact dir (never committed); the
/// aggregated report is committed separately.
///
/// Run: xcodebuild test -only-testing:"yuedu appTests/BrowserLayoutABHarnessTests"
@MainActor
struct BrowserLayoutABHarnessTests {

    struct CorpusBook: Decodable {
        let path: String
        let category: String
    }

    struct CorpusManifest: Decodable {
        let books: [CorpusBook]
    }

    struct ChapterResult {
        let spine: Int
        let browserAccepted: Bool
        let unsupported: [String]
        let browserPages: Int
        let legacyPages: Int
        let firstPageLatencyMs: Double
        let layoutTimeMs: Double
        let memoryDeltaKB: Int64
        let textSimilarity: Double
        let engineFailure: String?
    }

    struct BookResult {
        let title: String
        let category: String
        let chapterResults: [ChapterResult]
        let peakRSSDeltaMB: Double
    }

    // MARK: - Shared settings

    private var settings: ReaderRenderSettings {
        ReaderRenderSettings(
            theme: "paper",
            textColor: .black,
            backgroundColor: .white,
            fontSize: 17,
            lineHeightMultiple: 1.4,
            lineSpacing: 0,
            paragraphSpacing: 6,
            letterSpacing: 0,
            marginH: 12,
            marginV: 12,
            footerHeight: 24,
            contentInsets: UIEdgeInsets(top: 12, left: 12, bottom: 12, right: 12)
        )
    }

    private let renderSize = CGSize(width: 390, height: 800)
    /// Sample the first N chapters per book (real novels have hundreds).
    private let maxChaptersPerBook = 8
    /// Skip chapters larger than this many UTF-16 units (keeps runs bounded).
    private let maxChapterLength = 200_000

    // MARK: - Test

    @Test func runCorpusAB() async throws {
        let manifestURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("docs/browser-layout/corpus-manifest.json")
        let manifest = try JSONDecoder().decode(
            CorpusManifest.self,
            from: Data(contentsOf: manifestURL)
        )

        var bookResults: [BookResult] = []
        var summaries: [String] = []
        summaries.append("# Browser Layout Phase 2A — Corpus A/B Report")
        summaries.append("")
        summaries.append("_Generated by BrowserLayoutABHarnessTests; snapshot artifacts in the local cache dir._")
        summaries.append("")
        summaries.append("| Book | Category | Chapters | Accepted | Rejected | Engine failures | Parity failures | Page-count diffs | Median first-page (ms) | p95 first-page (ms) | Peak RSS Δ (MB) |")
        summaries.append("|---|---|---|---|---|---|---|---|---|---|---|")

        for book in manifest.books {
            guard FileManager.default.fileExists(atPath: book.path) else {
                summaries.append("| \((book.path as NSString).lastPathComponent) | \(book.category) | SKIPPED (missing) | - | - | - | - | - | - |")
                continue
            }
            let result = try await runBook(book)
            bookResults.append(result)
            summaries.append(summaryRow(result))
        }

        let report = summaries.joined(separator: "\n")
        let reportURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("docs/browser-layout/phase2a-report.md")
        try report.write(to: reportURL, atomically: true, encoding: .utf8)

        print("AB-REPORT\n\(report)")
        // The harness is informational; a run without ANY book is a failure.
        #expect(bookResults.count >= 10, "expected ≥10 corpus books, ran \(bookResults.count)")
    }

    // MARK: - Per-book

    private func runBook(_ book: CorpusBook) async throws -> BookResult {
        let session = try await PublicationSession.open(sourceURL: URL(fileURLWithPath: book.path))
        let chapterCount = min(session.chapters.count, maxChaptersPerBook)
        var results: [ChapterResult] = []
        let baselineMemory = MemoryStats.currentFootprint()
        var memoryPeak = baselineMemory

        // Package-declared vertical writing mode rejects every chapter (the
        // CSS scan alone misses package-level declarations).
        let packageVertical = session.epubWritingMode == .verticalRL

        for spine in 0..<chapterCount {
            let html = try await session.chapterHTML(at: spine)
            guard (html as NSString).length <= maxChapterLength else { continue }

            let chapterResult = await runChapter(
                session: session, spine: spine, bookPath: book.path,
                forceReject: packageVertical
            )
            results.append(chapterResult)
            memoryPeak = max(memoryPeak, MemoryStats.currentFootprint())
        }
        return BookResult(
            title: session.bookTitle,
            category: book.category,
            chapterResults: results,
            peakRSSDeltaMB: Double(memoryPeak - baselineMemory) / 1_048_576
        )
    }

    private func runChapter(session: PublicationSession, spine: Int, bookPath: String, forceReject: Bool) async -> ChapterResult {
        let start = CACurrentMediaTime()
        if bookPath.contains("洪武") {
            try? "start spine=\(spine)".write(toFile: "/tmp/harness-hongwu-\(spine).txt", atomically: true, encoding: .utf8)
        }

        // Browser side (independent of the reader UI).
        let adapter = EPUBBrowserLayoutResourceAdapter(session: session)
        let html = (try? await session.chapterHTML(at: spine)) ?? ""
        let css = await adapter.processedCSS(forChapter: spine)
        var scan = BrowserLayoutCapabilityScanner.scan(html: html, cssTexts: css)
        if forceReject {
            scan = BrowserLayoutCapabilityResult(
                supported: false,
                unsupportedFeatures: [.verticalWritingMode] + scan.unsupportedFeatures
            )
        }

        var browserPages = 0
        var firstPageLatency: TimeInterval = 0
        var layoutTime: TimeInterval = 0
        var browserVisible = ""
        var engineFailure: String? = nil

        if scan.supported {
            let images = await adapter.prefetchImages(
                forChapter: spine, html: html,
                renderWidth: renderSize.width - settings.contentInsets.left - settings.contentInsets.right
            )
            let config = BrowserLayoutConfig(
                renderWidth: renderSize.width - settings.contentInsets.left - settings.contentInsets.right,
                renderHeight: renderSize.height - settings.contentInsets.top - settings.contentInsets.bottom,
                rootFontSize: settings.fontSize,
                fontFamilies: [],
                textColor: settings.textColor,
                backgroundColor: settings.backgroundColor,
                contentInsets: settings.contentInsets,
                lineHeight: settings.lineHeightMultiple,
                fontResolver: adapter.fontResolver()
            )
            let document = BrowserLayoutDocument(html: html, cssTexts: css, config: config, imageLoader: { images[$0] })
            let layoutStart = CACurrentMediaTime()
            if let (pages, metrics) = try? await document.renderPagesAndMeasure(
                containerSize: renderSize
            ) {
                layoutTime = CACurrentMediaTime() - layoutStart
                browserPages = pages.count
                browserVisible = BrowserLayoutTestSupport.visibleText(pages, sourceText: document.lastSourceText)
                // The browser engine lays out atomically: page 0 is available
                // when layout completes, so first-page latency == layout time.
                firstPageLatency = metrics.total
                // Snapshot first 3 browser pages to the local artifact dir.
                for (index, page) in pages.prefix(3).enumerated() {
                    let list = DisplayListBuilder.build(for: page, sourceText: document.lastSourceText)
                    let image = DisplayListRenderer.render(list, size: renderSize)
                    writeSnapshot(image, book: bookPath, spine: spine, engine: "browser", page: index)
                }
            } else {
                engineFailure = "browserLayoutFailed"
            }
        }

        // Legacy side.
        let builder = EPUBAttributedStringBuilder(session: session, renderSize: renderSize)
        var legacyPages = 0
        var legacyText = ""
        if let result = try? await builder.buildChapter(
            at: spine,
            settings: settings,
            themeTextColor: settings.textColor,
            themeBackgroundColor: settings.backgroundColor
        ) {
            let paginator = CoreTextPaginator()
            let layout = await paginator.paginate(
                spineIndex: spine,
                attrStr: result.attributedString,
                renderSize: renderSize,
                fontSize: settings.fontSize,
                lineSpacing: settings.lineSpacing,
                paragraphSpacing: settings.paragraphSpacing,
                letterSpacing: settings.letterSpacing,
                contentInsets: settings.contentInsets
            )
            legacyPages = layout.pageRanges.count
            legacyText = result.attributedString.string
            for index in 0..<min(3, layout.pageRanges.count) {
                let image = renderLegacyPage(layout: layout, pageIndex: index)
                writeSnapshot(image, book: bookPath, spine: spine, engine: "legacy", page: index)
            }
        }

        let elapsedMs = (CACurrentMediaTime() - start) * 1000
        let similarity = textSimilarity(browserVisible, legacyText)
        if bookPath.contains("洪武") {
            try? """
            spine=\(spine) accepted=\(scan.supported) elapsedMs=\(Int(elapsedMs)) browserPages=\(browserPages) legacyPages=\(legacyPages)
            browserLen=\(browserVisible.count) legacyLen=\(legacyText.count) similarity=\(similarity)
            browserPrefix=\(String(browserVisible.prefix(60)))
            legacyPrefix=\(String(legacyText.prefix(60)))
            """.write(toFile: "/tmp/harness-hongwu-\(spine).txt", atomically: true, encoding: .utf8)
        }

        return ChapterResult(
            spine: spine,
            browserAccepted: scan.supported,
            unsupported: scan.unsupportedFeatures.map(\.description),
            browserPages: browserPages,
            legacyPages: legacyPages,
            firstPageLatencyMs: firstPageLatency * 1000,
            layoutTimeMs: layoutTime * 1000,
            memoryDeltaKB: 0,
            textSimilarity: similarity,
            engineFailure: engineFailure
        )
    }

    // MARK: - Helpers

    private func renderLegacyPage(layout: CoreTextPaginator.ChapterLayout, pageIndex: Int) -> UIImage {
        let renderer = UIGraphicsImageRenderer(size: renderSize)
        return renderer.image { context in
            CoreTextPageView.renderPage(
                layout: layout,
                pageIndex: pageIndex,
                in: context.cgContext,
                bounds: CGRect(origin: .zero, size: renderSize)
            )
        }
    }

    private func writeSnapshot(_ image: UIImage, book: String, spine: Int, engine: String, page: Int) {
        let base = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("yuedu-ab", isDirectory: true)
            .appendingPathComponent((book as NSString).lastPathComponent.replacingOccurrences(of: ".epub", with: ""), isDirectory: true)
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        let url = base.appendingPathComponent("s\(spine)-\(engine)-p\(page).png")
        try? image.pngData()?.write(to: url)
    }

    /// Windowed containment + order check, whitespace-insensitive.
    ///
    /// The legacy pipeline injects a chapter title and inserts spaces at block
    /// boundaries; the browser engine follows CSS (no space between blocks).
    /// Whitespace is NOT content, so both sides are stripped of ALL whitespace
    /// before comparison — the metric detects real character loss /
    /// duplication / reordering, never whitespace differences.
    private func textSimilarity(_ browser: String, _ legacy: String) -> Double {
        func normalize(_ s: String) -> String {
            // Whitespace is not content (legacy injects titles and block-edge
            // spaces; the browser follows CSS). Smart quotes are typography,
            // not content (legacy renders ' as ').
            s.replacingOccurrences(of: #"\s+"#, with: "", options: .regularExpression)
                .replacingOccurrences(of: "\u{FFFC}", with: "")
                .replacingOccurrences(of: "\u{2018}", with: "'")
                .replacingOccurrences(of: "\u{2019}", with: "'")
                .replacingOccurrences(of: "\u{201C}", with: "\"")
                .replacingOccurrences(of: "\u{201D}", with: "\"")
        }
        let a = normalize(browser)
        let b = normalize(legacy)
        if a.isEmpty && b.isEmpty { return 1 }
        // A chapter with legacy text but NO browser text is real content loss.
        if a.isEmpty || b.isEmpty { return 0 }
        guard a.count >= 200 else { return 1 }   // too short to window-check

        let windowLength = 200
        let stride = max(1, (a.count - windowLength) / 20)
        var hits = 0
        var checks = 0
        var previousLocation = -1
        let bNS = b as NSString
        let aChars = Array(a)

        var index = 0
        while index + windowLength <= a.count {
            let window = String(aChars[index..<(index + windowLength)])
            // Order check: windows must appear in monotonically non-decreasing
            // positions (catches reordering). Repeated substrings can make the
            // FIRST occurrence appear earlier than the previous window's — try
            // both the first and last occurrence, take the later position.
            let first = bNS.range(of: window)
            let last = bNS.range(of: window, options: .backwards)
            let positions = [first, last].compactMap { $0.location != NSNotFound ? $0.location : nil }
            if let orderedPosition = positions.filter({ $0 >= previousLocation }).max() {
                hits += 1
                previousLocation = orderedPosition
            }
            checks += 1
            index += stride
        }
        // Tail window (partial) so short chapters still get checked.
        if a.count > windowLength, checks == 0 || index < a.count {
            let tail = String(aChars[max(0, a.count - windowLength)...])
            if bNS.range(of: tail).location != NSNotFound { hits += 1 }
            checks += 1
        }
        return checks > 0 ? Double(hits) / Double(checks) : 1
    }

    private func summaryRow(_ result: BookResult) -> String {
        let accepted = result.chapterResults.filter { $0.browserAccepted }.count
        let rejected = result.chapterResults.filter { !$0.browserAccepted && $0.engineFailure == nil }.count
        let failures = result.chapterResults.filter { $0.engineFailure != nil }.count
        let parityFailures = result.chapterResults.filter { $0.browserAccepted && $0.textSimilarity < 0.95 }.count
        // Page-count agreement is the layout-regression proxy: a supported
        // chapter whose browser page count differs wildly from legacy suggests
        // blank/duplicate/missing pages.
        let pageCountDiffs = result.chapterResults.filter {
            $0.browserAccepted && abs($0.browserPages - $0.legacyPages) > max(1, $0.legacyPages / 4)
        }.count
        let latencies = result.chapterResults.map(\.firstPageLatencyMs).sorted()
        let median = latencies.isEmpty ? 0 : latencies[latencies.count / 2]
        let p95 = latencies.isEmpty ? 0 : latencies[min(latencies.count - 1, Int(Double(latencies.count) * 0.95))]
        return "| \(result.title.prefix(24)) | \(result.category) | \(result.chapterResults.count) | \(accepted) | \(rejected) | \(failures) | \(parityFailures) | \(pageCountDiffs) | \(Int(median)) | \(Int(p95)) | \(String(format: "%.1f", result.peakRSSDeltaMB)) |"
    }
}
