import Foundation

/// JIS X 0213 → Unicode and accent decomposition tables from aozora2html
/// (CC0), generated by `scripts/aozora_tables.py` into `Resources/Assets`.
/// `aozora-tables.manifest.json` records the upstream commit and checksums.
struct AozoraTables: Sendable {
    static let shared = AozoraTables.loadBundled()

    /// "1-2-24" → "ヿ". Values may be several scalars (1-4-87 is か゚) or lie
    /// outside the BMP (2-1-1 is U+20089).
    let characters: [String: String]
    /// Base letter plus mark, as written inside 〔…〕: "e'" → "é", "AE&" → "Æ".
    let accents: [String: String]

    init(characters: [String: String], accents: [String: String]) {
        self.characters = characters
        self.accents = accents
    }

    func character(plane: Int, row: Int, cell: Int) -> String? {
        characters["\(plane)-\(row)-\(cell)"]
    }

    func accent(_ sequence: String) -> String? {
        accents[sequence]
    }

    static func loadBundled(_ bundle: Bundle = .main) -> AozoraTables {
        let characters = dictionary(named: "aozora-jis2ucs", in: bundle)
        var accents: [String: String] = [:]
        for (sequence, code) in dictionary(named: "aozora-accent", in: bundle) {
            guard let character = characters[code] else {
                AppLogger.error("Aozora accent table names a JIS code the gaiji table lacks",
                                context: ["sequence": sequence, "code": code])
                continue
            }
            accents[sequence] = character
        }
        return AozoraTables(characters: characters, accents: accents)
    }

    private static func dictionary(named name: String, in bundle: Bundle) -> [String: String] {
        guard let url = bundle.url(forResource: name, withExtension: "json") else {
            AppLogger.error("Aozora table missing from the app bundle", context: ["resource": name])
            return [:]
        }
        do {
            return try JSONDecoder().decode([String: String].self, from: Data(contentsOf: url))
        } catch {
            AppLogger.error("Aozora table could not be read", error: error, context: ["resource": name])
            return [:]
        }
    }
}
